name: Module - Build Scene Hider eBPF

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v6

      - name: Download vmlinux Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: 'vmlinux-*'
          path: downloaded_vmlinux

      - name: Clone Scene-Port-Hider
        run: git clone https://github.com/Andrea-lyz/Scene-Port-Hider-by-eBPF.git ebpf_project

      - name: Build eBPF Module
        working-directory: ebpf_project
        run: |
          bash "${{ github.workspace }}/.github/scripts/_build_ebpf_module.sh" \
            "${{ github.workspace }}/downloaded_vmlinux" \
            "${{ github.workspace }}/ebpf_project"

      - name: Upload eBPF Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ScenePortHider-eBPF
          path: ebpf_project/output/*.zip
