name: Build GKI for Nezha

on:
  workflow_dispatch:
    inputs:
      ksu_variant:
        description: 'KernelSU Variant'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - MidoriSU-SuSFS
          - MidoriSU
          - MidoriXX
      create_release:
        description: 'Publish Release'
        required: false
        default: true
        type: boolean
      kernel_localversion:
        description: 'Spoof Kernel Name'
        required: true
        default: '-android16-5-g5a0e85dd9db0-ab14499855-4k'
        type: string
      build_timestamp:
        description: 'Spoof Build Time'
        required: true
        default: 'Wed Nov 26 11:16:14 UTC 2025'
        type: string
      build_epoch:
        description: 'SOURCE_DATE_EPOCH'
        required: true
        default: '1764155774'
        type: string

permissions:
  contents: write
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.config.outputs.release_tag }}
    steps:
      - id: config
        run: echo "release_tag=$(date +'%y%m%d%H%M')" >> $GITHUB_OUTPUT

  build_susfs:
    needs: setup
    if: inputs.ksu_variant == 'all' || inputs.ksu_variant == 'MidoriSU-SuSFS'
    uses: ./.github/workflows/build-susfs.yml
    with:
      sub_level: '23'
      kernel_localversion: ${{ inputs.kernel_localversion }}
      build_epoch: ${{ inputs.build_epoch }}
      build_timestamp: ${{ inputs.build_timestamp }}
      build_host: ${{ inputs.build_host }}
      build_user: ${{ inputs.build_user }}

  build_midorisu:
    needs: setup
    if: inputs.ksu_variant == 'all' || inputs.ksu_variant == 'MidoriSU'
    uses: ./.github/workflows/build-midorisu.yml
    with:
      sub_level: '23'
      kernel_localversion: ${{ inputs.kernel_localversion }}
      build_epoch: ${{ inputs.build_epoch }}
      build_timestamp: ${{ inputs.build_timestamp }}
      build_host: ${{ inputs.build_host }}
      build_user: ${{ inputs.build_user }}

  build_midorixx:
    needs: setup
    if: inputs.ksu_variant == 'all' || inputs.ksu_variant == 'MidoriXX'
    uses: ./.github/workflows/build-midorixx.yml
    with:
      sub_level: '23'
      kernel_localversion: ${{ inputs.kernel_localversion }}
      build_epoch: ${{ inputs.build_epoch }}
      build_timestamp: ${{ inputs.build_timestamp }}
      build_host: ${{ inputs.build_host }}
      build_user: ${{ inputs.build_user }}

  release:
    needs: [setup, build_susfs, build_midorisu, build_midorixx]
    if: |
      always() && 
      inputs.create_release == true &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          pattern: 'Kernel-*'
          path: release_zips
          merge-multiple: true
          
      - name: Download MidoriSU Manager APK
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo midori01/KernelSU --pattern "*.apk" --dir release_zips
    
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ needs.setup.outputs.release_tag }}"
          name: "Kernel Midori Build (${{ needs.setup.outputs.release_tag }})"
          files: |
            release_zips/*.zip
            release_zips/*.apk
