name: Build GKI Kernel

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Target device'
        required: true
        type: choice
        options:
          - popsicle
          - nezha
      toolchain:
        description: 'Toolchain'
        required: true
        type: choice
        options:
          - aosp-clang
          - zyc-clang
      ksu_variant:
        description: 'KernelSU variant'
        required: true
        type: choice
        options:
          - xxksu
          - kowsu
      sub_level:
        description: 'Kernel sublevel'
        required: false
        default: '23'
        type: string

jobs:
  build:
    name: ${{ inputs.ksu_variant }} ${{ inputs.device }} ${{ inputs.toolchain }}
    uses: ./.github/workflows/build-${{ inputs.ksu_variant }}.yml
    with:
      device: ${{ inputs.device }}
      toolchain: ${{ inputs.toolchain }}
      sub_level: ${{ inputs.sub_level }}
